def getCategories():
    products = []
    products.append(('Mobiles & Accessories',['Mobiles','Power Bank Pouches','Tablets','Mobile Accessories','Tablet Accessories','Landline Phones']))   
    products.append(('Mobiles',))
    products.append(('Tablets',))
    products.append(('Power Bank Pouches',))
    products.append(('Mobile Accessories',['Cases & Covers','Mobile Enhancements','Screen Protectors','Chargers','Cables','Styling & Maintenance','Power Banks','Car Accessories','Headsets (Mic)','Headphones','Stylus Pens','Batteries','Speakers','Memory Cards & Readers','Bluetooth Headsets (Mic)','Headphones Splitters','Smart Watches','Headphone Amplifiers','Sim Adapters','Sim Cutters','Charging Pads']))
    products.append(('Cases & Covers',))
    products.append(('Mobile Enhancements',['Mobile Accessories Combos','Docking Stations']))
    products.append(('Mobile Accessories Combos',))
    products.append(('Docking Stations',))
    products.append(('Screen Protectors',))
    products.append(('Chargers',['Wall Chargers','Portable Chargers','Car Chargers','Travel Adapters','Wireless Chargers']))
    products.append(('Wall Chargers',))
    products.append(('Portable Chargers',))
    products.append(('Car Chargers',))
    products.append(('Travel Adapters',))
    products.append(('Wireless Chargers',))
    products.append(('Cables',))
    products.append(('Styling & Maintenance',['Skins','Cleaning Kits','Phone Charms','Replacement Screens']))
    products.append(('Skins',))
    products.append(('Cleaning Kits',))
    products.append(('Phone Charms',))
    products.append(('Replacement Screens',))
    products.append(('Power Banks',))
    products.append(('Car Accessories',['Car Chargers','Mobile Holders','Car Kits','GPS Navigation Devices']))
    products.append(('Car Chargers',))
    products.append(('Mobile Holders',))
    products.append(('Car Kits',))
    products.append(('GPS Navigation Devices',))
    products.append(('Headsets (Mic)',))
    products.append(('Headphones',))
    products.append(('Stylus Pens',))
    products.append(('Batteries',))
    products.append(('Speakers',))
    products.append(('Memory Cards & Readers',['Mobile Memory Cards','Card Readers']))
    products.append(('Mobile Memory Cards',))
    products.append(('Card Readers',))
    products.append(('Bluetooth Headsets (Mic)',))
    products.append(('Headphones Splitters',))
    products.append(('Smart Watches',))
    products.append(('Headphone Amplifiers',))
    products.append(('Sim Adapters',))
    products.append(('Sim Cutters',))
    products.append(('Charging Pads',))
    products.append(('Tablet Accessories',['Tablet Cases & Covers','Tablet Screen Protectors','Tablet Chargers','Tablet Speakers','Tablet Cables','Tablet Memory Cards & Readers','Tablet Keyboards','Tablet Stylus Pens','Tablet Headphones','Tablet Bluetooth Headsets (Mic)']))
    products.append(('Tablet Cases & Covers',))
    products.append(('Tablet Screen Protectors',))
    products.append(('Tablet Chargers',['Tablet Portable Chargers']))
    products.append(('Tablet Portable Chargers',))
    products.append(('Tablet Memory Cards & Readers',['Tablet Memory Cards']))
    products.append(('Tablet Memory Cards',))
    products.append(('Tablet Speakers',))
    products.append(('Tablet Cables',))
    products.append(('Tablet Keyboards',))
    products.append(('Tablet Stylus Pens',))
    products.append(('Tablet Headphones',))
    products.append(('Tablet Bluetooth Headsets (Mic)',))
    products.append(('Landline Phones',))
    products.append(('Footwear',['Men\'s Footwear','Women\'s Footwear','Kid\'s Footwear']))
    products.append(('Men\'s Footwear',['Men Shoes','Men Sandals & Floaters','Men Slippers & Flip Flop']))
    products.append(('Men Shoes',['Men Casual Shoes','Men Sports Shoes','Men Formal Shoes','Men Ethnic Shoes']))
    products.append(('Men Casual Shoes',))
    products.append(('Men Sports Shoes',))
    products.append(('Men Formal Shoes',))
    products.append(('Men Ethnic Shoes',))
    products.append(('Men Sandals & Floaters',))
    products.append(('Men Slippers & Flip Flop',))
    products.append(('Women\'s Footwear',['Women Flats','Women Bellies','Women Heels','Women Wedges','Women Formal','Women Casual Shoes','Women Sports Shoes','Women Sports Sandals','Women Slippers & Flip Flop','Women Sandals']))
    products.append(('Women Flats',))
    products.append(('Women Bellies',))
    products.append(('Women Heels',))
    products.append(('Women Wedges',))
    products.append(('Women Formal',))
    products.append(('Women Casual Shoes',['Women Lifestyle','Women Loafers','Women Mocassins','Women Sneakers','Women Canvas','Women Boots']))
    products.append(('Women Lifestyle',))
    products.append(('Women Loafers',))
    products.append(('Women Mocassins',))
    products.append(('Women Sneakers',))
    products.append(('Women Canvas',))
    products.append(('Women Boots',))
    products.append(('Women Sports Shoes',['Women Trekking & Outdoors','Women Gym & Fitness','Women Running','Women Tennis','Women Walking']))
    products.append(('Women Trekking & Outdoors',))
    products.append(('Women Gym & Fitness',))
    products.append(('Women Running',))
    products.append(('Women Tennis',))
    products.append(('Women Walking',))
    products.append(('Women Sports Sandals',))
    products.append(('Women Slippers & Flip Flop',))
    products.append(('Women Sandals',['Women Formal Sandals']))
    products.append(('Women Formal Sandals',))
    products.append(('Kid\'s Footwear',['Girls','Boys']))
    products.append(('Girls',['Girls Sandals','Girls Clogs','Girls Flats & Bellies','Girls Casual Shoes','Girls Sports Shoes','Girls School Shoes','Girls Slippers & Flip Flop','Girls Booties']))
    products.append(('Girls Sandals',['Girls Sports Sandals','Girls Casual Sandals']))
    products.append(('Girls Sports Sandals',))
    products.append(('Girls Casual Sandals',))
    products.append(('Girls Clogs',))
    products.append(('Girls Flats & Bellies',['Girls Flats','Girls Bellies']))
    products.append(('Girls Flats',))
    products.append(('Girls Bellies',))
    products.append(('Girls Casual Shoes',))
    products.append(('Girls Sports Shoes',))
    products.append(('Girls School Shoes',))
    products.append(('Girls Slippers & Flip Flop',))
    products.append(('Girls Booties',))
    products.append(('Boys',['Boys Sandals','Boys Clogs','Boys Casual Shoes','Boys Sports Shoes','Boys School Shoes','Boys Slippers & Flip Flop']))
    products.append(('Boys Sandals',['Boys Casual Sandals','Boys Sports Sandals']))
    products.append(('Boys Casual Sandals',))
    products.append(('Boys Sports Sandals',))
    products.append(('Boys Clogs',))
    products.append(('Boys Casual Shoes',))
    products.append(('Boys Sports Shoes',))
    products.append(('Boys School Shoes',))
    products.append(('Boys Slippers & Flip Flop',))

    return products

def getProducts():
    products = []
    products.append(('Moto G', 'Motorola', 'Mobiles'))
    products.append(('Samsung Galaxy S3','Samsung','Mobiles'))
    products.append(('Sony Power Bank Pouch','Sony','Power Bank Pouches'))
    products.append(('DigiFlip Pro XT712','DigiFlip','Tablets'))
    products.append(('Lenovo S8 Tablet','Lenovo','Tablets'))
    products.append(('Moto Flip Cover for Moto G','Motorola','Cases & Covers'))
    products.append(('Chevron Back Cover Case With HD Screen Guard & 3.5mm Stereo Earphones For Xiaomi Redmi Note 4G Combo Set','Chevron','Mobile Accessories Combos'))
    products.append(('Belkin F8J045BT Dock (Silver)','Belkin','Docking Stations'))
    products.append(('nCase PSP-MT-XT1022 Screen Guard for Motorola Moto E','nCase','Screen Protectors'))
    products.append(('Samsung ATADU10IBECINU Battery Charger','Samsung','Wall Chargers'))
    products.append(('AGS Apple iPhone 4, 4S, 4G Battery Charger','Apple','Wall Chargers'))
    products.append(('Ambrane P-1000 Portable Charger (Black)','Ambrane','Portable Chargers'))
    products.append(('Epresent USBcarchargerw Car Charger (White)','Epresent','Car Chargers'))
    products.append(('Happy Funk Universal Travel Adaptor(White)','Happy Funk','Travel Adapters'))
    products.append(('Nokia DT-900 Wireless Charging Plate(Black)','Nokia','Wireless Chargers'))
    products.append(('Samsung APCBU10BBE USB Cable','Samsung','Cables'))
    products.append(('Callmate OTGMI Micro USB OTG Cable for Tablets and Mobiles','Callmate','Cables'))
    products.append(('Skintice SKIN3118 - Micromax Canvas Doodle 3 A102 Micromax Canvas Doodle 3 A102 Mobile Skin','Skintice','Skins'))
    products.append(('Lapcare 3-in-1 Screen Cleaning Kit with Blower for Mobiles||Computers||Laptops','Lapcare','Cleaning Kits'))
    products.append(('Wackypocket Moustache Black Phone Charm(Black)','Wackypocket','Phone Charms'))
    products.append(('Samsung Galaxy s3653 Digitizer 4.3 inch Replacement Screen(Samsung Galaxy Core)','Samsung','Replacement Screens'))
    products.append(('DigiFlip Power Bank 6600 mAh PC008 (with Two USB Outputs)','DigiFlip','Power Banks'))
    products.append(('Samsung Car Charger CAD300UBEC/INU(Black)','Samsung','Car Chargers'))
    products.append(('Fly Car Mobile Stand Holder Mount(Black)','Fly','Mobile Holders'))
    products.append(('Leoxsys Wireless 3.5mm Bluetooth Car Audio Music Receiver with Mic Handsfree Stereo Output Car Kit','Leoxsys','Car Kits'))
    products.append(('TomTom Via 120 GPS Device','TomTom','GPS Navigation Devices'))
    products.append(('Sony Mh750 Wired Headset(Black)','Sony','Headsets (Mic)'))
    products.append(('Skullcandy S2IKDY-102 Ink\'d 2 Headset(Rasta)','Skullcandy','Headsets (Mic)'))
    products.append(('Sennheiser HD 180(Black, Over-the-ear)','Sennheiser','Headphones'))
    products.append(('JBL T100A Wired Headphones(White, Earbud)','JBL','Headphones'))
    products.append(('Griffin High-sensitivity Stylus for Smartphones and Tablets(Black)','Griffin','Stylus Pens'))
    products.append(('Nokia Battery BL-5C','Nokia','Batteries'))
    products.append(('Samsung battery Duos S7562(Black)','Samsung','Batteries'))
    products.append(('DigiFlip PS009 Wired Mini USB Speaker(Blue, 2 Channel)','DigiFlip','Speakers'))
    products.append(('JBL Pulse Bluetooth Speaker(1 Channel)','JBL','Speakers'))
    products.append(('Samsung MicroSDHC 16 GB 48 MB/s Class 10 Evo','Samsung','Mobile Memory Cards'))
    products.append(('Quantum QHM 5570 Card Reader (Red)','Quantum','Card Readers'))
    products.append(('Samsung BHM1100NBEGINU In-the-ear Wireless Headset without Charger','Samsung','Bluetooth Headsets (Mic)'))
    products.append(('MJR Audio Splitter 3.5 mm Headphone Splitter(White)','MJR','Headphones Splitters'))
    products.append(('Motorola Moto 360 Smartwatch (Black)','Motorola','Smart Watches'))
    products.append(('FiiO Fujiyama E06 Portable Headphone Amplifier','Fii0','Headphone Amplifiers'))
    products.append(('Noosy One In All Nano Sim Adapter (Stainless Steel)','Noosy','Sim Adapters'))
    products.append(('ENTIF JSRCUTTER03 Sim Cutter(Stainless Steel)','ENTIF','Sim Cutters'))
    products.append(('Its Our Studio Al50531 Charging Pad','Its Our Studio','Charging Pads'))
    products.append(('DigiFlip Book Cover for DigiFlip Pro XT801(Black)','DigiFlip','Tablet Cases & Covers'))
    products.append(('nCase PSP-SM-T211 Screen Guard for Samsung 7-inch Galaxy Tab 3','nCase','Tablet Screen Protectors'))
    products.append(('Yoobao yb-6012 Universal Power Pack 5200 mAh(Silver)','Yoobao','Tablet Portable Chargers'))
    products.append(('Samsung MicroSDXC 64 GB 48 MB/s Class 10 Evo','Samsung','Tablet Memory Cards'))
    products.append(('JBL Flip II Wireless Portable Stereo Speaker(Black, 1 Channel)','JBL','Tablet Speakers'))
    products.append(('iEnhance iConnect - 30 Pin to USB Cable for iPhone / iPad / iPod','iEnhance','Tablet Cables'))
    products.append(('Microware Leather Case USB Standard Keyboard(Black)','Microware','Tablet Keyboards'))
    products.append(('Saco STK7 USB Standard Keyboard (Black)','Saco','Tablet Keyboards'))
    products.append(('Cubix Crystal Diamond Stylus Touch Pen and Fine Ball Pen for Lenovo Yoga 8 Tablet','Cubix','Tablet Stylus Pens'))
    products.append(('Sony MDR-ZX750BN Wired & Wireless Bluetooth Headphones (White, Over the Head)','Sony','Tablet Headphones'))
    products.append(('iBall IB073 Wired Bluetooth Headset(Black)','iBall','Tablet Bluetooth Headsets (Mic)'))
    products.append(('Gigaset A490 Cordless Landline Phone(Black)','Gigaset','Landline Phones'))
    products.append(('Reebok Luxor Lp Running Shoes','Reebok','Men Casual Shoes'))
    products.append(('Fila Boxer Sneakers','Fila','Men Casual Shoes'))
    products.append(('Puma Atom Fashion Ind. Running Shoes','Puma','Men Sports Shoes'))
    products.append(('Lotto Rapid Running Shoes','Lotto','Men Sports Shoes'))
    products.append(('Prolific Shadow Loop Slip On','Prolific','Men Formal Shoes'))
    products.append(('Lee Cooper Slip On Shoes','Lee Cooper','Men Formal Shoes'))
    products.append(('Ridhi Sidhi Sober Jutis','Ridhi Sidhi','Men Ethnic Shoes'))
    products.append(('Bareskin New Brown Leather Jalsa With Black Sole Jutis','Bareskin','Men Ethnic Shoes'))
    products.append(('Ethics Flats','Ethics','Men Sandals & Floaters'))
    products.append(('Sparx Sandals','Sparx','Men Sandals & Floaters'))
    products.append(('Diesel Slippers','Diesel','Men Slippers & Flip Flop'))
    products.append(('Adidas Adze Flip Flops','Adidas','Men Slippers & Flip Flop'))
    products.append(('Do Bhai Flats','Do Bhai','Women Flats'))
    products.append(('Shezone Flats','Shezone','Women Flats'))
    products.append(('Anupamaa Soft Gold Mojaris','Anupamaa','Women Bellies'))
    products.append(('Sam Stefy Leather Heels','Sam Stefy','Women Heels'))
    products.append(('Cenizas Collage Fly Wedges','Cenizas','Women Wedges'))
    products.append(('Trilokani T69 Slip On Shoes','Trilokani','Women Formal'))
    products.append(('Puma Lifestyle Shoes','Puma','Women Lifestyle'))
    products.append(('Infiniti Blue Loafers','Infiniti','Women Loafers'))
    products.append(('DONE BY NONE Zig That Zag Mocassins','DONE BY NONE','Women Mocassins'))
    products.append(('Puma Wirko Xc Wn\'S Sneakers','Puma','Women Sneakers'))
    products.append(('Reebok On Court Iv Lp Canvas Shoes','Reebok','Women Canvas'))
    products.append(('Nell Boots','Nell','Women Boots'))
    products.append(('Do Bhai Honey-Black Boots','Do Bhai','Women Boots'))
    products.append(('Quechua Forclaz Novadry Lady Hiking & Trekking Shoes','Quechua Forclaz Novadry','Women Trekking & Outdoors'))
    products.append(('Adidas Ax2 W Trekking & Outdoors Shoes','Adidas','Women Gym & Fitness'))
    products.append(('Reebok Fresh Start Iii Lp Running Shoes','Reebok','Women Running'))
    products.append(('Puma Descendant Ind Wns Running Shoes','Puma','Women Running'))
    products.append(('Khadim\'s Pro Tennis Shoes','Khadim','Women Tennis'))
    products.append(('Skechers Go Walk 3 Walking Shoes','Skechers','Women Walking'))
    products.append(('Fila Pearl Flip Flops','Fila','Women Sports Sandals'))
    products.append(('Oricum Flats','Oricum','Women Sports Sandals'))
    products.append(('Superdry Flip Flops','Superdry','Women Slippers & Flip Flop'))
    products.append(('Belle Gambe Heels','Belle','Women Formal Sandals'))
    products.append(('Anupamaa Pinky Sand Wedges','Anupamaa','Girls Sports Sandals'))
    products.append(('Gelukkig Flats','Gelukkig','Girls Casual Sandals'))
    products.append(('U & ME Caterpillar Blue 22 Sandals','U & ME','Girls Clogs'))
    products.append(('Trilokani Super Fancy Sandals','Trilokani','Girls Flats'))
    products.append(('Cutecumber Flower Bellies','Cutecumber','Girls Bellies'))
    products.append(('ProASE Laminated Badminton Badminton Shoes','ProASE','Girls Casual Shoes'))
    products.append(('Skechers Go Run Ride Sports Shoes','Skechers','Girls Sports Shoes'))
    products.append(('Hi-Look School Monk Strap Shoes','Hi-Look','Girls School Shoes'))
    products.append(('Radition Butterfly Flip Flops','Radition','Girls Slippers & Flip Flop'))
    products.append(('Do Bhai KING-BROWN KING-BROWN Boots','Do Bhai','Girls Booties'))
    products.append(('Adidas Akwah 9 K Sports Sandals','Adidas','Boys Sports Sandals'))
    products.append(('Tweety Sports Sandals','Tweety','Boys Casual Sandals'))
    products.append(('U & ME Sandals','U & ME','Boys Clogs'))
    products.append(('Shoe Mate Smps207 casual Casual Shoes','Shoe Mate','Boys Casual Shoes'))
    products.append(('Ros 1025-White Walking Shoes','Ros','Boys Sports Shoes'))
    products.append(('Sierra School Shoes','Sierra','Boys School Shoes'))
    products.append(('Puma Owl Ind. Flip Flops','Puma','Boys Slippers & Flip Flop'))
    products.append(('Puma Zebra Ind. Flip Flops','Puma','Boys Slippers & Flip Flop'))

    return products